name: Let it bee!
on: [workflow_dispatch]
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: head ./examples/important_document.txt -n 6
    
    - uses: actions/upload-artifact@v2
      with:
        name: Bee Artifact
        path: ./examples/important_document.txt
