name: HTTP Bee
on: [workflow_dispatch]
jobs:
  get-data:
    name: "Get data"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install request
    - run: npm install fs
    - run: node ./data/get_data.js
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: data/result.txt
  print-data:
    name: "Print data"
    needs: get-data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ./
    - run: head result.txt -n 12