name: Run a lottery
on: [workflow_dispatch]
jobs:
  choose-winner:
    runs-on: ubuntu-latest
    name: Pulling a winner
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x ./examples/winner.sh
    - run: ./examples/winner.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Winner
        path: ./winner.txt
